### ISSUE TITLE
Not compatible with Intellij IDEA 2020.2

### ISSUE THREAD

**Issue by Thunderforge** [Haehnchen/idea-localization-plugin#2]
When running Intellij IDEA 2020.2, this error appears:

> Plugin Error: Plugin "Localization" is incompatible (until build 201.SNAPSHOT < IU-202.6397.94).

![image](https://user-images.githubusercontent.com/6200170/89073210-a4d45280-d33f-11ea-9e9c-8c8629cc252d.png)

**Comment by julkue** [comment]
Same issue here.

**Comment by julkue** [comment]
Seems to be fixed with https://github.com/Haehnchen/idea-localization-plugin/commit/c87e9d6c78421785e3f69d96a8acba04a1fcb029

**Comment by Thunderforge** [comment]
Yes, version 0.0.6 compatible and I'm able to run it in Intellij IDEA 2020.2.
